### PR TITLE
Update projections.r

### PR DESCRIPTION
**Pull request by TheMathNinja**
New league ID, allow for 2021's 18 week season.

### CODE REVIEW

**Comment by zamorarr** [comment]
Hey! Thanks for the PR. Sorry I lost track of this project. The changes look good, but when I try and test it I am getting an error:

```R
ffespn_projections(2021, 0)

# Error: Can't subset columns that don't exist.
# x Column `season_outlook` doesn't exist.
# Run `rlang::last_error()` to see where the error occurred.] 
```

Was there a different command that you used to test? I'll try in a bit to remove the `season_outlook` column since it probably doesn't exist yet.

**Comment by TheMathNinja** [comment]
I just replaced the league ID in the one spot I saw it, but it looks like the error request you're getting is still seeing the old leagueID somewhere else. Sorry I didn't go through all the R files, just the one. I haven't run any proper tests, unfortunately (still a bit amateur for that); I just made sure that the URL called actually exists for the new league. The league and the projections exist, but whatever `season_outlook` is may not.

**Comment by zamorarr** [comment]
no worries. I think I found the problem and will fix it shortly

**Comment by zamorarr** [comment]
Thanks! The code is updated now. Feel free to re-install with the latest version

**Comment by zamorarr** [comment]
closes #10

**Pull request merged**
